
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path as P

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox, ttk
from ruamel.yaml import YAML


OUTPUT_PATH = P(__file__).parent
ASSETS_PATH = OUTPUT_PATH / P(r"Assets/login_frame")
ACCOUNTS_DIR = P('./Accounts')
ACCOUNTS_DIR.mkdir(exist_ok=True)
USERS_FILE = ACCOUNTS_DIR / 'users.yaml'
yaml = YAML()

# Function to read user data from the YAML file
def read_users():
    if USERS_FILE.exists():
        with open(USERS_FILE, "r") as file:
            return yaml.load(file) or {}
    return {}

# Function to write user data to the YAML file
def write_users(users):
    with open(USERS_FILE, "w") as file:
        yaml.dump(users, file)

def relative_to_assets(path: str) -> P:
    return ASSETS_PATH / P(path)

def login():
        username = entry_1.get()
        password = entry_2.get()
        users = read_users()

        if username in users and users[username] == password:
            messagebox.showinfo("Login", "Login successful!")
        else:
            messagebox.showerror("Login", "Invalid username or password.")


window = Tk()

window.geometry("1080x616")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 616,
    width = 1080,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1080.0,
    616.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    806.3641967773438,
    307.2890319824219,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    273.60699462890625,
    307.2890319824219,
    image=image_image_2
)

canvas.create_text(
    88.95953369140625,
    165.43359375,
    anchor="nw",
    text="Hello,",
    fill="#06D6A0",
    font=("Montserrat Regular", 40 * -1)
)

canvas.create_text(
    88.95953369140625,
    203.60971069335938,
    anchor="nw",
    text="Welcome!",
    fill="#06D6A0",
    font=("Montserrat Black", 48 * -1)
)

canvas.create_text(
    152.0,
    75.0,
    anchor="nw",
    text="Arti-san\n",
    fill="#000000",
    font=("Montserrat ExtraBold", 24 * -1)
)

canvas.create_text(
    90.63092041015625,
    285.0645446777344,
    anchor="nw",
    text="Email/Username",
    fill="#000000",
    font=("Montserrat SemiBold", 13 * -1)
)

email_entry = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    275.3185272216797,
    329.35618591308594,
    image=email_entry
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=94.95953369140625,
    y=306.79254150390625,
    width=360.7179870605469,
    height=43.127288818359375
)

canvas.create_text(
    90.63092041015625,
    363.61956787109375,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Montserrat SemiBold", 13 * -1)
)

pass_entry = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    275.3185272216797,
    407.9111785888672,
    image=pass_entry
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    show="*"
)
entry_2.place(
    x=94.95953369140625,
    y=385.3475341796875,
    width=360.7179870605469,
    height=43.127288818359375
)

login_button = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=login_button,
    borderwidth=0,
    highlightthickness=0,
    command=login,
    relief="flat"
)
button_1.place(
    x=90.63092041015625,
    y=453.8741149902344,
    width=177.36907958984375,
    height=41.78453063964844
)

sign_button = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=sign_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=285.0,
    y=454.0,
    width=177.36907958984375,
    height=41.78453063964844
)

forgot_button = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=forgot_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=91.0,
    y=511.0,
    width=371.0,
    height=41.78453063964844
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    114.52020263671875,
    94.23126220703125,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    807.0,
    47.0,
    image=image_image_4
)

canvas.create_text(
    775.0,
    35.0,
    anchor="nw",
    text="Arti-san\n",
    fill="#FFFFFF",
    font=("Montserrat ExtraBold", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
