
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path as P

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox, ttk
from ruamel.yaml import YAML
import subprocess


OUTPUT_PATH = P().parent
ASSETS_PATH = OUTPUT_PATH / P(r"Assets/login_frame")
ACCOUNTS_DIR = P('./Accounts')
ACCOUNTS_DIR.mkdir(exist_ok=True)
USERS_FILE = ACCOUNTS_DIR / 'users.yaml'
ICON = P('./Assets/logour.png')
yaml = YAML()


# Function to read user data from the YAML file
def read_users():
    if USERS_FILE.exists():
        with open(USERS_FILE, "r") as file:
            return yaml.load(file) or {}
    return {}

def relative_to_assets(path: str) -> P:
    return ASSETS_PATH / P(path)

def login():
    username_or_email = entry_1.get()  # Get the entered username or email
    password = entry_2.get()
    users = read_users()

    # Check if the entered username or email exists in users and if the password matches
    for user_data in users.values():
        if ('username' in user_data and user_data['username'] == username_or_email and user_data['password'] == password) or \
           ('email' in user_data and user_data['email'] == username_or_email and user_data['password'] == password):
            messagebox.showinfo("Login", "Login successful!")
            return

    messagebox.showerror("Login", "Invalid username or email or password.")

def signup_script():
        script_path = "Scripts/signup.py"
        subprocess.run(['python', script_path])
def forgot_script():
        script_path = "Scripts/I_forgot.py"
        subprocess.run(['python', script_path])

def icon(window):
    img = PhotoImage(file=ICON)
    window.tk.call('wm', 'iconphoto', window._w, img)

window = Tk()
window.geometry("1080x616")
window.configure(bg = "#FFFFFF")
window.title("Welcome to Arti-san")
icon(window)

canvas = Canvas(window, bg = "#FFFFFF", height = 616, width = 1080, bd = 0, highlightthickness = 0, relief = "ridge")
canvas.place(x = 0, y = 0)
canvas.create_rectangle(0.0, 0.0, 1080.0, 616.0, fill="#FFFFFF", outline="")

login_bg = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image( 806.3641967773438, 307.2890625, image=login_bg)

gradient_bg = PhotoImage(file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(273.60693359375, 307.2890625, image=gradient_bg)

gray_grad = PhotoImage(file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(273.60693359375, 307.2890625, image=gray_grad)

hello_bg = PhotoImage(file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(275.0, 202.0, image=hello_bg)

canvas.create_text(105.95953369140625, 153.43359375, anchor="nw",
    text="Hello,", fill="#06D6A0", font=("Montserrat Regular", 40 * -1)
)
canvas.create_text(105.95953369140625, 191.6097412109375, anchor="nw",
    text="Welcome!", fill="#06D6A0", font=("Montserrat Black", 48 * -1)
)
canvas.create_text(152.0, 75.0, anchor="nw",
    text="Arti-san\n", fill="#000000", font=("Montserrat ExtraBold", 24 * -1)
)

# Email Entry
canvas.create_text(90.63092041015625, 285.0645446777344, anchor="nw",
    text="Email/Username", fill="#000000", font=("Montserrat SemiBold", 13 * -1))
entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(275.3185272216797, 329.35618591308594, image=entry_image_1)
entry_1 = Entry(bd=0, bg="#FFFFFF", fg="#000716", highlightthickness=0)
entry_1.place(x=94.95953369140625, y=306.79254150390625, width=360.7179870605469, height=43.127288818359375)

# Pass Entry
canvas.create_text(90.63092041015625, 363.61956787109375, anchor="nw",
    text="Password", fill="#000000", font=("Montserrat SemiBold", 13 * -1))
entry_image_2 = PhotoImage(file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(275.3185272216797, 407.9111785888672, image=entry_image_2)
entry_2 = Entry(bd=0, bg="#FFFFFF", fg="#000716", highlightthickness=0, show="*")
entry_2.place(x=94.95953369140625, y=385.3475341796875, width=360.7179870605469, height=43.127288818359375)

# Login Button
login_b = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(image=login_b, borderwidth=0, highlightthickness=0, command=login, relief="flat")
button_1.place(x=90.63092041015625, y=453.8741149902344, width=177.36907958984375, height=41.78453063964844)
login_hover = PhotoImage(file=relative_to_assets("button_hover_1.png"))
def button_1_hover(e):
    button_1.config(
        image=login_hover
    )
def button_1_leave(e):
    button_1.config(
        image=login_b
    )
button_1.bind('<Enter>', button_1_hover)
button_1.bind('<Leave>', button_1_leave)

# Signup Button
signup_b = PhotoImage(file=relative_to_assets("button_2.png"))
button_2 = Button(image=signup_b, borderwidth=0, highlightthickness=0, command=signup_script, relief="flat")
button_2.place(x=285.0, y=454.0, width=177.36907958984375, height=41.78453063964844)
signup_hover = PhotoImage(file=relative_to_assets("button_hover_2.png"))
def button_2_hover(e):
    button_2.config(
        image=signup_hover
    )
def button_2_leave(e):
    button_2.config(
        image=signup_b
    )
button_2.bind('<Enter>', button_2_hover)
button_2.bind('<Leave>', button_2_leave)

# Forgot Button
I_forgor = PhotoImage(file=relative_to_assets("button_3.png"))
button_3 = Button(image=I_forgor, borderwidth=0, highlightthickness=0, command=forgot_script, relief="flat")
button_3.place(x=91.0, y=511.0, width=371.0, height=41.78453063964844)
forgor_hover = PhotoImage(file=relative_to_assets("button_hover_3.png"))
def button_3_hover(e):
    button_3.config(
        image=forgor_hover
    )
def button_3_leave(e):
    button_3.config(
        image=I_forgor
    )
button_3.bind('<Enter>', button_3_hover)
button_3.bind('<Leave>', button_3_leave)

# logo
logo = PhotoImage(file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(114.52020263671875, 94.23126220703125, image=logo)

image_image_6 = PhotoImage(file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(807.0, 45.0, image=image_image_6)

canvas.create_text(773.0, 33.0, anchor="nw",
    text="Arti-san\n", fill="#FFFFFF", font=("Montserrat ExtraBold", 15 * -1)
)

window.resizable(False, False)
window.mainloop()