
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path as P

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox, ttk
from ruamel.yaml import YAML


OUTPUT_PATH = P().parent
ASSETS_PATH = OUTPUT_PATH / P(r"Assets/signup_frame")
ACCOUNTS_DIR = P('./Accounts')
ACCOUNTS_DIR.mkdir(exist_ok=True)
USERS_FILE = ACCOUNTS_DIR / 'users.yaml'
yaml = YAML()


def relative_to_assets(path: str) -> P:
    return ASSETS_PATH / P(path)


window = Tk()

window.geometry("1079x616")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 616,
    width = 1079,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1079.169677734375,
    616.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    805.9417724609375,
    307.27342224121094,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    272.594970703125,
    307.27342224121094,
    image=image_image_2
)

address = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    267.30934143066406,
    418.53604316711426,
    image=address
)
address_entry = Entry( 
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,

)
address_entry.place(
    x=87.0936279296875,
    y=395.98974609375,
    width=360.4314270019531,
    height=43.092594146728516
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    265.74989318847656,
    340.561372756958,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=85.5341796875,
    y=318.01507568359375,
    width=360.4314270019531,
    height=43.092594146728516
)

canvas.create_text(
    142.0,
    51.0,
    anchor="nw",
    text="Arti-san\n",
    fill="#000000",
    font=("Montserrat ExtraBold", 24 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    105.0,
    71.0,
    image=image_image_3
)

canvas.create_text(
    80.0,
    115.0,
    anchor="nw",
    text="Hello,",
    fill="#06D6A0",
    font=("Montserrat Regular", 40 * -1)
)

canvas.create_text(
    80.0,
    153.1761474609375,
    anchor="nw",
    text="New User!",
    fill="#06D6A0",
    font=("Montserrat Black", 48 * -1)
)

fname = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    165.83489990234375,
    262.5636444091797,
    image=fname
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=86.0,
    y=240.0,
    width=159.6697998046875,
    height=43.127288818359375
)

lname = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    358.5,
    262.5636444091797,
    image=lname
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=271.0,
    y=240.0,
    width=175.0,
    height=43.127288818359375
)

canvas.create_text(
    81.0,
    221.0,
    anchor="nw",
    text="Last name",
    fill="#000000",
    font=("Montserrat SemiBold", 13 * -1)
)

canvas.create_text(
    81.0,
    297.0,
    anchor="nw",
    text="Contact Number",
    fill="#000000",
    font=("Montserrat SemiBold", 13 * -1)
)

canvas.create_text(
    83.0,
    374.0,
    anchor="nw",
    text="Address",
    fill="#000000",
    font=("Montserrat SemiBold", 13 * -1)
)

canvas.create_text(
    268.0,
    221.0,
    anchor="nw",
    text="First name",
    fill="#000000",
    font=("Montserrat SemiBold", 13 * -1)
)

sign_button = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=sign_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=81.0,
    y=510.0,
    width=371.0,
    height=41.78453063964844
)
window.resizable(False, False)
window.mainloop()
